version: '3'
services:
  web:  # Flask (web) application container
    build: ./
    ports:
      - "5000:5000"  # portforwarding from Flask to on localhost:5000 
    depends_on:
      - redis
  redis:  # key-value store for visit counts
    image: redis:alpine
